---
driver:
  name: vagrant
  customize:
    memory: 512

provisioner:
  name: chef_zero

platforms:
# We don't have every platform that this might work on, or every
# version as the latest. The behavior in this cookbook is dependent on
# platform families.
- name: ubuntu-14.04
- name: centos-6.6
  # To run test-kitchen for OS X, create a box for 10.10, and add it to vagrant
- name: macosx-10.10
  driver:
    box: chef/macosx-10.10

suites:
- name: debian
  run_list:
    - recipe[build-essential]
    - recipe[vagrant]
    - recipe[test]
  excludes:
    - centos-6.6
    - macosx-10.10
  attributes:
    vagrant:
      plugins:
        - vagrant-omnibus

- name: rhel
  run_list:
    - recipe[build-essential]
    - recipe[vagrant]
    - recipe[test]
  excludes:
    - ubuntu-14.04
    - macosx-10.10
  attributes:
    vagrant:
      plugins:
        - vagrant-omnibus

- name: osx
  run_list:
    - recipe[build-essential]
    - recipe[vagrant]
    - recipe[test]
  excludes:
    - ubuntu-14.04
    - centos-6.6
  attributes:
    vagrant:
      plugins:
        - vagrant-omnibus
